=== pypi-data/pypi-mirror-73/packages/bas-web-map-inventory/bas-web-map-inventory-0.4.0.tar.gz/bas-web-map-inventory-0.4.0/bas_web_map_inventory/resources/json_schemas/data-resources-schema.json
{
  "$id": "https://metadata-standards.data.bas.ac.uk/bas-web-map-inventory-configuration-schemas/data-resources-schema-v1.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "BAS Web Map Inventory - Data resources configuration schema",
  "description": "Data resources schema used by the BAS Web Map Inventory and other related services",
  "definitions": {
    "services": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "wms",
          "wfs"
        ]
      }
    },
    "geometry": {
      "oneOf": [
        {
          "type": "string",
          "enum": [
            "point",
            "linestring",
            "polygon",
            "3d-polygon",
            "multi-point",
            "multi-linestring",
            "multi-polygon",
            "3d-multi-polygon",
            "geometry-collection"
          ]
        },
        {
          "type": "null"
        }
      ]
    },
    "server": {
      "type": "object",
      "required": [
        "id",
        "label",
        "hostname",
        "type"
      ],
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string"
        },
        "label": {
          "type": "string"
        },
        "hostname": {
          "type": "string"
        },
        "type": {
          "type": "string",
          "enum": [
            "geoserver"
          ]
        },
        "version": {
          "type": "string"
        }
      }
    },
    "namespace": {
      "type": "object",
      "required": [
        "id",
        "label",
        "relationships"
      ],
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string"
        },
        "label": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "namespace": {
          "type": "string"
        },
        "relationships": {
          "type": "object",
          "required": [
            "servers"
          ],
          "additionalProperties": false,
          "properties": {
            "servers": {
              "type": "string"
            }
          }
        }
      }
    },
    "repository": {
      "type": "object",
      "required": [
        "id",
        "label",
        "type",
        "relationships"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "label": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "type": {
          "type": "string"
        },
        "namespace": {
          "type": "string"
        },
        "relationships": {
          "type": "object",
          "required": [
            "namespaces"
          ],
          "additionalProperties": false,
          "properties": {
            "namespaces": {
              "type": "string"
            }
          }
        }
      }
    },
    "style": {
      "type": "object",
      "required": [
        "id",
        "label",
        "type",
        "relationships"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "label": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "type": {
          "type": "string"
        },
        "relationships": {
          "type": "object",
          "required": [
            "namespaces"
          ],
          "additionalProperties": false,
          "properties": {
            "namespaces": {
              "type": [
                "string",
                "null"
              ]
            }
          }
        }
      }
    },
    "layer": {
      "type": "object",
      "required": [
        "id",
        "label",
        "type",
        "relationships"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "label": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "type": {
          "type": "string"
        },
        "services": {
          "$ref": "#/definitions/services"
        },
        "relationships": {
          "type": "object",
          "required": [
            "namespaces",
            "repositories",
            "styles"
          ],
          "additionalProperties": false,
          "properties": {
            "namespaces": {
              "type": "string"
            },
            "repositories": {
              "type": "string"
            },
            "styles": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        }
      }
    },
    "layer-group": {
      "type": "object",
      "required": [
        "id",
        "label",
        "relationships"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "label": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "services": {
          "$ref": "#/definitions/services"
        },
        "geometry": {
          "$ref": "#/definitions/geometry"
        },
        "relationships": {
          "type": "object",
          "required": [
            "namespaces",
            "layers",
            "styles"
          ],
          "additionalProperties": false,
          "properties": {
            "namespaces": {
              "type": "string"
            },
            "layers": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "styles": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        }
      }
    },
    "postgis-repository": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/repository"
        },
        {
          "type": "object",
          "required": [
            "type",
            "hostname",
            "database",
            "schema"
          ],
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "postgis"
              ]
            },
            "hostname": {
              "type": "string"
            },
            "database": {
              "type": "string"
            },
            "schema": {
              "type": "string"
            }
          }
        }
      ]
    },
    "jpg2000-repository": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/repository"
        },
        {
          "type": "object",
          "required": [
            "type"
          ],
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "jpg2000"
              ]
            }
          }
        }
      ]
    },
    "imagemosaic-repository": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/repository"
        },
        {
          "type": "object",
          "required": [
            "type"
          ],
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "imagemosaic"
              ]
            }
          }
        }
      ]
    },
    "geotiff-repository": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/repository"
        },
        {
          "type": "object",
          "required": [
            "type"
          ],
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "geotiff"
              ]
            }
          }
        }
      ]
    },
    "ecw-repository": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/repository"
        },
        {
          "type": "object",
          "required": [
            "type"
          ],
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "ecw"
              ]
            }
          }
        }
      ]
    },
    "worldimage-repository": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/repository"
        },
        {
          "type": "object",
          "required": [
            "type"
          ],
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "worldimage"
              ]
            }
          }
        }
      ]
    },
    "shapefile-repository": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/repository"
        },
        {
          "type": "object",
          "required": [
            "type"
          ],
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "shapefile"
              ]
            }
          }
        }
      ]
    },
    "shapefiles-directory-repository": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/repository"
        },
        {
          "type": "object",
          "required": [
            "type"
          ],
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "shapefiles-directory"
              ]
            }
          }
        }
      ]
    },
    "oracle-repository": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/repository"
        },
        {
          "type": "object",
          "required": [
            "type"
          ],
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "oracle"
              ]
            },
            "hostname": {
              "type": "string"
            },
            "database": {
              "type": "string"
            },
            "schema": {
              "type": "string"
            }
          }
        }
      ]
    },
    "geogig-repository": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/repository"
        },
        {
          "type": "object",
          "required": [
            "type"
          ],
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "geogig"
              ]
            }
          }
        }
      ]
    },
    "cascaded-wms-repository": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/repository"
        },
        {
          "type": "object",
          "required": [
            "type"
          ],
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "cascaded-wms"
              ]
            }
          }
        }
      ]
    },
    "sld-style": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/style"
        },
        {
          "type": "object",
          "required": [
            "type"
          ],
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "sld"
              ]
            }
          }
        }
      ]
    },
    "layers-vector": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/layer"
        },
        {
          "type": "object",
          "required": [
            "type",
            "geometry"
          ],
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "vector"
              ]
            },
            "geometry": {
              "$ref": "#/definitions/geometry"
            },
            "table_view": {
              "type": [
                "string",
                "null"
              ]
            }
          }
        }
      ]
    },
    "layers-raster": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/layer"
        },
        {
          "type": "object",
          "required": [
            "type",
            "geometry"
          ],
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "raster"
              ]
            }
          }
        }
      ]
    },
    "layers-cascaded-wms": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/layer"
        },
        {
          "type": "object",
          "required": [
            "type",
            "geometry"
          ],
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "wms"
              ]
            }
          }
        }
      ]
    }
  },
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "servers": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/server"
      }
    },
    "namespaces": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/namespace"
      }
    },
    "repositories": {
      "type": "array",
      "items": {
        "oneOf": [
          {
            "$ref": "#/definitions/postgis-repository"
          },
          {
            "$ref": "#/definitions/jpg2000-repository"
          },
          {
            "$ref": "#/definitions/imagemosaic-repository"
          },
          {
            "$ref": "#/definitions/geotiff-repository"
          },
          {
            "$ref": "#/definitions/ecw-repository"
          },
          {
            "$ref": "#/definitions/worldimage-repository"
          },
          {
            "$ref": "#/definitions/shapefile-repository"
          },
          {
            "$ref": "#/definitions/shapefiles-directory-repository"
          },
          {
            "$ref": "#/definitions/oracle-repository"
          },
          {
            "$ref": "#/definitions/geogig-repository"
          },
          {
            "$ref": "#/definitions/cascaded-wms-repository"
          }
        ]
      }
    },
    "styles": {
      "type": "array",
      "items": {
        "oneOf": [
          {
            "$ref": "#/definitions/sld-style"
          }
        ]
      }
    },
    "layers": {
      "type": "array",
      "items": {
        "oneOf": [
          {
            "$ref": "#/definitions/layers-vector"
          },
          {
            "$ref": "#/definitions/layers-raster"
          },
          {
            "$ref": "#/definitions/layers-cascaded-wms"
          }
        ]
      }
    },
    "layer-groups": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/layer-group"
      }
    }
  }
}

=== pypi-data/pypi-mirror-73/packages/bas-web-map-inventory/bas-web-map-inventory-0.4.0.tar.gz/bas-web-map-inventory-0.4.0/tests/data/data.json
{
    "servers": [
        {
            "id": "01DRS53XAG5E85MJNYTA6WPTBM",
            "label": "test-server-1",
            "hostname": "test-server-1.example.com",
            "type": "geoserver",
            "version": "testing"
        }
    ],
    "namespaces": [
        {
            "id": "01DWY9DVWWATVMETQDD5P5JN98",
            "label": "test-namespace-1",
            "title": "-",
            "namespace": "-",
            "relationships": {
                "servers": "01DRS53XAG5E85MJNYTA6WPTBM"
            }
        }
    ],
    "repositories": [
        {
            "id": "01DWY9DVWWEJWQX8QCKYVD3TK5",
            "label": "test-repository-1",
            "title": "Test Repository 1",
            "type": "postgis",
            "hostname": "test-postgis-1.example.com",
            "database": "test",
            "schema": "test",
            "relationships": {
                "namespaces": "01DWY9DVWWATVMETQDD5P5JN98"
            }
        }
    ],
    "styles": [
        {
            "id": "01DWY9DVWW7S05WXQN6ZXY84G3",
            "label": "test-style-1",
            "title": "-",
            "type": "sld",
            "relationships": {
                "namespaces": "01DWY9DVWWATVMETQDD5P5JN98"
            }
        }
    ],
    "layers": [
        {
            "id": "01DWY9DVWXQTZPYP4JYFN4Q7PS",
            "label": "test-layer-1",
            "title": "Test Layer 1",
            "type": "vector",
            "geometry": "point",
            "services": [
                "wms",
                "wfs"
            ],
            "table_view": "test",
            "relationships": {
                "namespaces": "01DWY9DVWWATVMETQDD5P5JN98",
                "repositories": "01DWY9DVWWEJWQX8QCKYVD3TK5",
                "styles": [
                    "01DWY9DVWW7S05WXQN6ZXY84G3"
                ]
            }
        }
    ],
    "layer-groups": [
        {
            "id": "01DWY9DVWX0F7Y1P5DR0BRK4TZ",
            "label": "test-layer-group-1",
            "title": "Test Layer Group 1",
            "geometry": "point",
            "services": [
                "wms",
                "wfs"
            ],
            "relationships": {
                "namespaces": "01DWY9DVWWATVMETQDD5P5JN98",
                "layers": [
                    "01DWY9DVWXQTZPYP4JYFN4Q7PS"
                ],
                "styles": [
                    "01DWY9DVWW7S05WXQN6ZXY84G3"
                ]
            }
        }
    ]
}
